---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bookstore.example.com
  resources:
  - books
  - bookstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookstore.example.com
  resources:
  - books/finalizers
  - bookstores/finalizers
  verbs:
  - update
- apiGroups:
  - bookstore.example.com
  resources:
  - books/status
  - bookstores/status
  verbs:
  - get
  - patch
  - update
