kind: Book
apiVersion: bookstore.example.com/v1
metadata:
  name: the-lord-of-the-rings2-copyof
  namespace: hadera-books
spec:
  title: The Lord of the Rings2
  price: 20
  genre: Fantasy
  copyOf:
    namespace: hadera-books
    name: the-lord-of-the-rings2