apiVersion: bookstore.example.com/v1
kind: Book
metadata:
  labels:
    app.kubernetes.io/name: bookstore-operator
    app.kubernetes.io/managed-by: kustomize
  name: the-lord-of-the-rings
  namespace: jerusalem-books
spec:
  title: The Lord of the Rings
  price: 10
  genre: Fantasy
  copyOf:
    namespace: tel-aviv-books
    name: the-lord-of-the-rings
